services:
  postgres:
    image: postgres:17
    container_name: db_fastlog
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - rede-local
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/fastlog-ddl.sql:/docker-entrypoint-initdb.d/fastlog-ddl.sql

  adminer:
    image: adminer
    container_name: adminer_fastlog
    ports:
      - "8080:8080"
    networks:
      - rede-local

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-rastreamento
    ports:
      - "8000:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_APP_ENVIRONMENT}
    networks:
      - rede-local
    depends_on:
      - postgres

networks:
  rede-local:

volumes:
  pgdata:
