services:
  postgres:
    image: postgres:17
    container_name: db_fastlog
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=FASTLOG
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./../../database/fastlog-ddl.sql:/docker-entrypoint-initdb.d/fastlog-ddl.sql

  adminer:
    image: adminer
    container_name: adminer_fastlog
    ports:
      - 8080:8080

volumes:
  pgdata:
