server:
  port: 8000

spring:
  application:
    name: api-rastreamento
  profiles:
    active: ${SPRING_APP_ENVIRONMENT:prod}

  sql:
    init:
      continue-on-error: true

  jpa:
    generate-ddl: false
    show-sql: false
