spring:
  datasource:
    url: jdbc:postgresql://fastlog-prod.ctg6686gojod.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: ${DATASOURCE_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 0
      maximum-pool-size: 15
      connection-timeout: 3000
      idle-timeout: 300000
      max-lifetime: 600000
      initialization-fail-timeout: -1
      validation-timeout: 1000
