server:
  port: 8000

spring:
  application:
    name: gestao-usuarios
  profiles:
    active: ${ENVIRONMENT:prod}  # Definindo o perfil ativo com a variável ENVIRONMENT

  sql:
    init:
      continue-on-error: true
