name: Deploy

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:

  deploy:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    env:
      IMAGE_VERSION: ${{ github.run_number }}

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Configurar TAG
      id: vars
      run: echo "IMAGE_VERSION=$(date +%s)" >> $GITHUB_ENV
  
    - name: Construir e enviar imagem
      run: |
        docker build -t uken49/api-rastreamento:${{ env.IMAGE_VERSION }} -t uken49/api-rastreamento:latest .
        docker push uken49/api-rastreamento:${{ env.IMAGE_VERSION }}
        docker push uken49/api-rastreamento:latest

    - name: Update ECS Service
      run: |
        aws ecs update-service \
          --cluster fastlog_rastreamento \
          --service service-web \
          --force-new-deployment
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1