name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [21, 17]

    steps:
      - uses: actions/checkout@v4

      - name: Configurando Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: adopt
          java-version: ${{ matrix.java-version }}

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

  test:
    needs: build

    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
    restore-keys: |
      ${{ runner.os }}-maven-

    steps:
      - name: Testes unitários
        run: |
          cd backend/rastreamento
          mvn -B -e -q install -DENVIRONMENT=test

      - name: Teste com Checkstyle
        run: mvn checkstyle:check
